os: linux
dist: bionic
language: python
python:
    - 3.8
    - 3.7
    - 3.6

install: pip install .
before_script: pip install coverage python-coveralls
script: python3 -m unittest discover tests
after_success: coveralls